{% set name = "argopy" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0755851e3c63c46646056ca9ffe6f78847d89c2abc229bbf7bdcf10abb52aac3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - decorator >=5.1
    - netcdf4 >=1.5.3
    - python >={{ python_min }}
    - aiohttp >=3.7
    - erddapy >0.8
    - fsspec >=0.8
    - netCDF4 >=1.5.3
    - packaging >=20.4
    - requests >=2.28
    - scipy >=1.5
    - toolz >=0.8.2
    - xarray >=0.18,<2024.3
    # imports pkg_resources
    - setuptools >=42

test:
  imports:
    - argopy
    - argopy.data_fetchers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/euroargodev/argopy
  summary: A python library for Argo data beginners and experts
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
